# Name of the app
name: ""

# DNS names
hosts: []

certificate:
  # Name of the certificate
  name: ""

  # Namespace to create the certificate in
  namespace: "istio-system"

  # Secret to create for the certificate
  secretName: ""

  issuer:
    name: cert-manager-issuer
    kind: ClusterIssuer
    group: cert-manager.io

gateway:
  # Name of the gateway
  name: ""

  # Namespace to create the gateway in
  namespace: "istio-system"

  # Any additional servers, allows templating
  additionalServers: []
    # - port:
    #     number: 443
    #     name: https
    #     protocol: HTTPS
    #   tls:
    #     mode: SIMPLE
    #     credentialName: '{{ template "chart.certificate.secret" . }}'
    #   hosts:
    #     - url

service:
  # Name of the virtual service
  name: ""

  # Destination to service
  # destination:
  #   host: "service.namespace.svc.cluster.local"
  #   port: 3000