default:
  source:
    repoURL: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      createNamespace: true

applications:
  metrics-server:
    namespace: kube-system
    sources:
      default:
        repoURL: https://kubernetes-sigs.github.io/metrics-server
        helm:
          valuesObject:
            replicas: 1
            metrics:
              enabled: true
            serviceMonitor:
              enabled: true
