argocd-apps:
  default:
    project: "default"
    source:
      repoURL: "git@github.com:exzeo-devops/argocd-system.git"
    revisionHistoryLimit: 10
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  applications:
    metrics-server:
      namespace: kube-system
      sources:
        default:
          repoURL: https://kubernetes-sigs.github.io/metrics-server
          targetRevision: "x"
          chart: "metrics-server"
          helm:
            valuesObject:
              replicas: 1
              metrics:
                enabled: true
              serviceMonitor:
                enabled: true