apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "chart.service.name" . }}
spec:
  hosts:
{{ include "chart.hosts" . | indent 4 }}
  gateways:
    - {{ .Values.gateway.namespace }}/{{ template "chart.gateway.name" . }}
{{ .Values.service.route | toYaml | indent 2  }}