name: '[CI/CD] Update README metadata'

on: pull_request
  # pull_request_target:
  #   branches:
  #     - main
  #   paths:
  #     - 'charts/*/values.yaml'

# Remove all permissions by default
permissions: {}
jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm

      - name: Checkout charts
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          path: charts
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ./.github/configs/ct-lint.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "changed_charts=$charts" >> $GITHUB_OUTPUT
          fi

      - name: Execute readme-generator-for-helm
        env:
          DIFF_URL: "${{github.event.pull_request.diff_url}}"
          TEMP_FILE: "${{runner.temp}}/pr-${{github.event.number}}.diff"
        run: |
          CHARTS=(${{ steps.list-changed.outputs.changed_charts }})
          for chart in "${CHARTS[@]}"; do
            echo "Updating README.md for ${chart}"
            readme-generator --values "charts/${chart}/values.yaml" --readme "charts/${chart}/README.md"
          done

      - name: Push changes
        run: |
          # Push all the changes
          cd charts
          if git status -s | grep charts; then
            git config user.name "DevOps"
            git config user.email "devops@exzeo.com"
            git add . && git commit -am "Update README.md with readme-generator-for-helm" --signoff && git push
          fi