name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-changed.outputs.matrixArray }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ./.github/configs/ct-lint.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "changed_charts=$charts" >> $GITHUB_OUTPUT
            echo "matrixArray=$(echo ${charts[@]} | jq -n)" >> $GITHUB_OUTPUT
          fi

      # - name: Run chart-testing (lint)
      #   run: ct lint --config ./.github/configs/ct-lint.yaml --lint-conf ./.github/configs/lintconf.yaml --target-branch ${{ github.event.repository.default_branch }}

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.8.0
      #   if: steps.list-changed.outputs.changed == 'true'
      #   with:
      #     config: .github/configs/kind-config.yaml

      # - name: Deploy latest ArgoCD CRDs when testing ArgoCD extensions
      #   if: |
      #     contains(steps.list-changed.outputs.changed_charts, 'argocd-apps')
      #   run: |
      #     helm repo add argo https://argoproj.github.io/argo-helm
      #     helm template argo/argo-cd --namespace argocd --set server.extensions.enabled=true -s templates/crds/* | kubectl apply -f -

      # - name: Run chart-testing (install)
      #   run: ct install --config ./.github/configs/ct-install.yaml --target-branch ${{ github.event.repository.default_branch }}

      # - name: Read Helm Chart
      #   id: chart
      #   uses: jacobtomlinson/gha-read-helm-chart@master
      #   with:
      #     path: path/to/chart

      # - name: Print outputs
      #   run: |
      #     echo "Name - ${{ steps.chart.outputs.name }}"
      #     echo "Version - ${{ steps.chart.outputs.version }}"
      #     echo "App Version - ${{ steps.chart.outputs.appVersion }}"

  release:
    needs: [lint-test]
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     value: ${{ needs.lint-test.outputs.matrix }}
    steps:
      - name: Push PR images
        run: |
          echo ${{ needs.lint-test.outputs.matrix }}